name: quakespasm-beidl
version: 0.93.1
grade: stable
summary: An engine for iD software's Quake.
description: |
  QuakeSpasm is a modern, cross-platform Quake 1 engine based on FitzQuake.
  
  It includes support for 64 bit CPUs and custom music playback, a new sound driver, some graphical niceities, and numerous bug-fixes and other improvements.

  This release of Quakespasm utilizes the SDL2 framework.
  
  Note to snap packagers:
   Additionally, other snaps can consume its content via a content interface plug. Consuming snaps could use following snapcraft.yaml snippet to add the interface.
  
  plugs:
    quake-engine:
    content: quake-engine
    interface: content
    target: $SNAP/quake-engine
    default-provider: quakespasm-beidl:quake-engine
   
  Within the consuming snap the content would be exposed at "$SNAP/quake-engine", ie:
     /snap/the-consuming-snap/current/quake-engine
     /var/lib/snapd/snap/the-consuming-snap/current/quake-engine
   
   Under certain circumstances it could be necessary to manually connect the interface, ie:
     snap connect the-consuming-snap:quake-engine quakespasm-beidl:quake-engine
  
confinement: strict

apps:
  quakespasm:
    command: desktop-launch quakespasm
    plugs: [ wayland, x11, desktop, home, opengl, pulseaudio, removable-media, network, joystick ]
  quakespasm-launch:
    command: desktop-launch quakespasm-launch
    plugs: [ wayland, x11, desktop, home, opengl, pulseaudio, removable-media, network, joystick ]

slots:
  quake-engine:
    content: quake-engine
    interface: content
    read:
      - $SNAP

parts:
  quakespasm:
    source: https://sourceforge.net/projects/quakespasm/files/Source/quakespasm-0.93.1.tgz/download
    source-type: tar
    source-checksum: sha1/aca08d7bea6085bc7b755fad1e83ef976b542c1e
    plugin: make
    override-build: |
      cd Quake
      make USE_SDL2=1 -j4
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin
      install -m 755 quakespasm $SNAPCRAFT_PART_INSTALL}/bin/
    build-packages:
      - make
      - build-essential
      - libgl1-mesa-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-net-dev
      - libpulse-dev
      - libvulkan-dev
      - libwayland-dev
      - libvorbis-dev
      - libmad0-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0
      - libpulse0
      - libvorbis0a
      - libmad0
      - libwayland-client0
      - zenity
    prime:
      - bin/
      - lib/
      - share/
      - usr/
    after: [ desktop-glib-only ]
  wrapper:
    source: .
    plugin: dump
    organize:
      quakespasm-launch: bin/quakespasm-launch
    after: [ quakespasm ]
